services:
  nats:
    image: nats:2.11-alpine
    container_name: ap2-nats
    command: ["--http_port", "${NATS_MONITORING_PORT}"]
    ports:
      - "${NATS_PORT}:4222"
      - "${NATS_MONITORING_PORT}:8222"

  doctor-db:
    image: postgres:16
    container_name: doctor-db
    environment:
      POSTGRES_DB: ${DOCTOR_DB_NAME}
      POSTGRES_USER: ${DOCTOR_DB_USER}
      POSTGRES_PASSWORD: ${DOCTOR_DB_PASSWORD}
    ports:
      - "${DOCTOR_DB_PORT}:5432"
    volumes:
      - doctor_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DOCTOR_DB_USER} -d ${DOCTOR_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  doctor:
    build:
      context: .
      dockerfile: doctor/Dockerfile
    container_name: doctor-service
    ports:
      - "${DOCTOR_GRPC_PORT}:50051"
    environment:
      DATABASE_URL: postgres://${DOCTOR_DB_USER}:${DOCTOR_DB_PASSWORD}@doctor-db:5432/${DOCTOR_DB_NAME}?sslmode=disable
      NATS_URL: ${NATS_URL}
    depends_on:
      doctor-db:
        condition: service_healthy

  appointment-db:
    image: postgres:16
    container_name: appointment-db
    environment:
      POSTGRES_DB: ${APPOINTMENT_DB_NAME}
      POSTGRES_USER: ${APPOINTMENT_DB_USER}
      POSTGRES_PASSWORD: ${APPOINTMENT_DB_PASSWORD}
    ports:
      - "${APPOINTMENT_DB_PORT}:5432"
    volumes:
      - appointment_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${APPOINTMENT_DB_USER} -d ${APPOINTMENT_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  appointment:
    build:
      context: .
      dockerfile: appointment/Dockerfile
    container_name: appointment-service
    ports:
      - "${APPOINTMENT_GRPC_PORT}:50052"
    environment:
      DATABASE_URL: postgres://${APPOINTMENT_DB_USER}:${APPOINTMENT_DB_PASSWORD}@appointment-db:5432/${APPOINTMENT_DB_NAME}?sslmode=disable
      DOCTOR_SERVICE_ADDR: ${DOCTOR_SERVICE_ADDR}
      NATS_URL: ${NATS_URL}
    depends_on:
      appointment-db:
        condition: service_healthy
      doctor:
        condition: service_started

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    container_name: notification-service
    environment:
      NATS_URL: ${NATS_URL}
    depends_on:
      nats:
        condition: service_started

volumes:
  doctor_pgdata:
  appointment_pgdata:
